# Generated by Django 2.2 on 2020-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('need_help', 'Нужна помошь'), ('can_help', 'Могу помочь'), ('can_consult', 'Могу проконсультировать')], default='need_help', max_length=50, verbose_name='Тема')),
                ('number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('group', models.CharField(choices=[('medicine', 'Лекарства'), ('finance', 'Финансы'), ('consultation', 'Консультация'), ('injection', 'Капельница / уколы'), ('another', 'Другое')], default='medicine', max_length=50, verbose_name='Тема')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
