# Generated by Django 2.2 on 2020-07-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('to_check', 'На проверке'), ('deactivated', 'Деактивированный')], default='active', max_length=50, verbose_name='Статус'),
        ),
    ]
