# Generated by Django 2.2 on 2020-07-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200705_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('deactivated', 'Деактивированный')], default='active', max_length=50, verbose_name='Статус'),
        ),
    ]
