# Generated by Django 2.2 on 2020-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200705_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('need_help', 'Нужна помощь'), ('can_help', 'Могу помочь')], default='need_help', max_length=50, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='group',
            field=models.CharField(choices=[('---', '---'), ('medicine', 'Лекарства'), ('injection', 'Инъекции'), ('finance', 'Финансы'), ('auto', 'Авто'), ('consultation', 'Консультация'), ('another', 'Другое')], default='---', max_length=50, verbose_name='Тема'),
        ),
    ]
